### ISSUE TITLE
'Naiset -> Takit' link redirects to 'Naiset-tarvikkeet'

### ISSUE THREAD

**Issue by SamuliPolvi** [ToniIltanen/VT_T6#1]
### Expected behavior
When selecting `Naiset -> Takit` link from dropdown, user should be redirected to `Naiset-takit` page.

### Actual behavior
User gets redirected to `Naiset-tarvikkeet`

### Steps to reproduce the behavior
From navbar dropdown, select `Naiset` and then `Takit`
Take a look at the page header

**Comment by ToniIltanen** [comment]
fixed
